### ISSUE TITLE
As a developer, I want a "hello world" webpage, so that we have a foundation on which other features can be built

### ISSUE THREAD

**Issue by antoneekstrom** [axoxelol1/dat257-hasse-andersson#5]
- [x] A webpage shows the text Hello World!
- [x] Is using Next.js
- [ ] Is working on all group members' machines

**Comment by MechaFlex** [comment]
- [] A webpage shows the text Hello World!
- [] Is using Next.js
- [] Is working on all group members machines

**Comment by antoneekstrom** [comment]
> Is working on all group members' machines

@LilleLink @axoxelol1 hello friends, can you make sure that you are also able to run the client code on your machines?

**Comment by axoxelol1** [comment]
Works without hiccups on my linux machine :+1:
