### ISSUE TITLE
As a user, I'd like to see a visually pleasing image of the campus in the background of the site

### ISSUE THREAD

**Issue by jenssandgren** [axoxelol1/dat257-hasse-andersson#63]
- [x] Take a nice picture of Chalmers
- [x] Implement the picture on site
- [x] Blur the picture
- [x] Make the picture consistent on mobile view

Optional
- [x] Collage

**Comment by simonengstrm** [comment]
Still issues with this? Thought I solved it with the merge but apparently not.
